<a href="https://colab.research.google.com/github/InfiSmile/ML/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install numpy

## <font color='orange'>What is NumPy</font>

<ul><li>Provides multi-dimensional array object.</li>
    <li>Provides tools for working with arrays.</li>
</ul>

## <font color='green'>Why use NumPy (vs List)</font>

<ol>
    <li>Size</li>
    <li>Performance</li>
    <li>Operations</li>
</ol>

### Performance comparision

In [ ]:
import numpy as np
import time

In [ ]:
time.time()

In [ ]:
a = [1,2,3], b =[2,1,0]
c = [3,3, 3]

In [ ]:
def list_version(size_of_array):
    t = time.time()
    a = range(size_of_array)
    b = range(size_of_array)
    for i in range(len(a)):
        c = [a[i] + b[i] for i in range(len(a)) ]
    return time.time() - t

In [ ]:
def numpy_version(size_of_array):
    t = time.time()
    a = np.arange(size_of_array)
    b = np.arange(size_of_array)
    c = a + b
    return time.time() - t

In [ ]:
size_of_array = 10000
print('Time taken using list (sec):', list_version(size_of_array))
print('Time taken using Numpy (sec):', numpy_version(size_of_array))

In [ ]:
list(range(0,5))

In [ ]:
numpy_version(size_of_array)/list_version(size_of_array)

### Operations

In [ ]:
x = list(range(10))
y = list(range(10))
x + y

In [ ]:
x = np.arange(10)
y = np.arange(10)
x + y

# <font color='blue'>What we will learn:</font>

<ol>
    <li>Creating numpy arrays</li>
    <li>Array with random numbers</li>
    <li>Array methods and attributes</li>
    <li>Indexing and Slicing</li>
    <li>NumPy Operations</li>
    <li>Storing and Reading NumPy arrays</li>
</ol>

## <font color='green'>1. Creating numpy arrays</font>

### From List

In [ ]:
a = [2,3,5,7,3,10]

In [ ]:
a.append(79)

In [ ]:
a

[2, 3, 5, 7, 3, 10, 79]

In [ ]:
type(a)

list

In [ ]:
a2 = np.array(a)
a2

array([ 2,  3,  5,  7,  3, 10, 79])

In [ ]:
type(a2)

numpy.ndarray

In [ ]:
b = [[1,2,5],[4,3,10]]

In [ ]:
np.array(b)

array([[ 1,  2,  5],
       [ 4,  3, 10]])

In [ ]:
c = [[34, 56, 23], [23, 67, 90], [35, 87, 92], [35, 87, 92], [35, 87, 92]]
np.array(c)

array([[34, 56, 23],
       [23, 67, 90],
       [35, 87, 92],
       [35, 87, 92],
       [35, 87, 92]])

### Using arange

In [ ]:
a = np.arange(0, #starting number
              10) #Stop number - excluded
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0, #start
          10, #stop
          3) #step

array([0, 3, 6, 9])

### Array using 0s and 1s

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.zeros((4,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
np.ones((4,6,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

### linspace

In [ ]:
np.linspace(1, #start number
            10, #Last number - not excluded
            5)  #How many numbers

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

### eye matrix

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## <font color='green'>2. Array using random numbers</font>

#### <font color='blue'>rand</font> - Using uniform distribution

In [ ]:
np.random.rand(4)

array([0.58084122, 0.63038185, 0.43533893, 0.97498956])

In [ ]:
np.random.rand(4)

In [ ]:
np.random.rand(5,10)

array([[0.58358379, 0.01714003, 0.27212986, 0.69617202, 0.05771997,
        0.75376031, 0.98714858, 0.03521877, 0.56140316, 0.83416379],
       [0.90204387, 0.11457523, 0.99075897, 0.17987308, 0.74336817,
        0.79811279, 0.33931218, 0.5477854 , 0.35463095, 0.30624147],
       [0.34255099, 0.26785662, 0.48081651, 0.84375366, 0.86573152,
        0.89688217, 0.07440229, 0.86782417, 0.28102709, 0.71295362],
       [0.98247486, 0.63489468, 0.13251361, 0.31836751, 0.64351083,
        0.40329961, 0.62507102, 0.40218628, 0.35763516, 0.87351367],
       [0.82962942, 0.08373897, 0.58919704, 0.01202424, 0.21805197,
        0.73150459, 0.79206131, 0.11986485, 0.45507194, 0.84613586]])

In [ ]:
x = 0.42014271
type(x)

#### <font color='blue'>randn</font> - Using normal distribution

In [ ]:
np.random.randn(4,3)

array([[ 0.78689651,  0.7578806 , -0.24242273],
       [-0.25696771, -0.05076801,  1.10417794],
       [ 0.31383224,  0.3806631 ,  0.07483312],
       [ 0.52441146, -2.09637446,  0.51096043]])

#### <font color='blue'>randint</font> - generating random integer(s)

In [ ]:
np.random.randint(5,20)

14

In [ ]:
np.random.randint(5,20,6)

array([ 5,  8, 17, 12,  8, 15])

In [ ]:
np.random.randint(5,20,(5,4))

array([[ 5,  7,  5,  7],
       [ 9,  5, 11,  9],
       [10, 13, 15,  6],
       [19,  7,  6, 14],
       [ 7, 13,  7,  9]])

#### <font color='blue'>Seed</font> - Bringing sanity to randomness

In [ ]:
np.random.randint(1,100,3)

array([54, 87, 40])

In [ ]:
np.random.seed(1)
np.random.randint(1,100,3)

array([38, 13, 73])

## <font color='orange'>3. Array methods and attributes</font>

### Shape

In [ ]:
a = np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
b = np.random.randn(4,3)
b

array([[-0.52817175, -1.07296862,  0.86540763],
       [-2.3015387 ,  1.74481176, -0.7612069 ],
       [ 0.3190391 , -0.24937038,  1.46210794],
       [-2.06014071, -0.3224172 , -0.38405435]])

In [ ]:
np.ndim(a)

1

In [ ]:
np.ndim(b)

2

In [ ]:
print(a.shape)

(20,)


In [ ]:
print(b.shape)

(4, 3)


In [ ]:
c = np.random.randn(5,2)
c

array([[ 1.13376944, -1.09989127],
       [-0.17242821, -0.87785842],
       [ 0.04221375,  0.58281521],
       [-1.10061918,  1.14472371],
       [ 0.90159072,  0.50249434]])

In [ ]:
np.ndim(c)

2

In [ ]:
c.shape

(5, 2)

### Reshape

In [ ]:
c = a.reshape(4,5)
print(c.shape)
c

(4, 5)


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

### max, min, argmax and argmin

In [ ]:
b = np.random.rand(3,4)
b

array([[0.01828828, 0.75014431, 0.98886109, 0.74816565],
       [0.28044399, 0.78927933, 0.10322601, 0.44789353],
       [0.9085955 , 0.29361415, 0.28777534, 0.13002857]])

In [ ]:
b.max()

0.9888610889064947

In [ ]:
b.argmax()

2

In [ ]:
print(b.min())
print(b.argmin())

0.018288277344191806
0


### Array data type

In [ ]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
a.dtype

dtype('int64')

In [ ]:
b

array([[0.01828828, 0.75014431, 0.98886109, 0.74816565],
       [0.28044399, 0.78927933, 0.10322601, 0.44789353],
       [0.9085955 , 0.29361415, 0.28777534, 0.13002857]])

In [ ]:
b.dtype

In [ ]:
a.astype('float32')

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19.], dtype=float32)

## <font color='green'>4. Indexing and Slicing</font>

#### Using brackets

In [ ]:
a = np.arange(11,25)
a

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
a[1]

12

In [ ]:
a[2:6]

array([13, 14, 15, 16])

In [ ]:
#Specific elements
a[[0,3,6]]

array([11, 14, 17])

In [ ]:
#Updating specific elements
a[3:5] = 100
a

array([ 11,  12,  13, 100, 100,  16,  17,  18,  19,  20,  21,  22,  23,
        24])

### Two dimensional array indexing and slicing

In [ ]:
b = np.array([[10,32,6,7,8], [90, 45, 32 , 89, 50],
              [33, 66, 99, 22, 55], [23, 56, 98, 45, 65]])
b

array([[10, 32,  6,  7,  8],
       [90, 45, 32, 89, 50],
       [33, 66, 99, 22, 55],
       [23, 56, 98, 45, 65]])

In [ ]:
#indexing row
b[1]

array([90, 45, 32, 89, 50])

In [ ]:
#Specific element
b[2][3]

22

In [ ]:
#Same as above
b[2,3]

In [ ]:
b[:3]

array([[10, 32,  6,  7,  8],
       [90, 45, 32, 89, 50],
       [33, 66, 99, 22, 55]])

In [ ]:
#Specific rows and columns
b
b[:2,2:]

array([[ 6,  7,  8],
       [32, 89, 50]])

### Custom indexing

In [ ]:
b = np.array([[10,32,6,7,8], [90, 45, 32 , 89, 50],
              [33, 66, 99, 22, 55], [23, 56, 98, 45, 65]])
b

array([[10, 32,  6,  7,  8],
       [90, 45, 32, 89, 50],
       [33, 66, 99, 22, 55],
       [23, 56, 98, 45, 65]])

In [ ]:
b[:2,(1,3)] #All Rows, (1 Coloumn, 3 Coloumn)

array([[32,  7],
       [45, 89]])

### Subset

In [ ]:
b

array([[10, 32,  6,  7,  8],
       [90, 45, 32, 89, 50],
       [33, 66, 99, 22, 55],
       [23, 56, 98, 45, 65]])

In [ ]:
c = b[:2,1:]
c

array([[32,  6,  7,  8],
       [45, 32, 89, 50]])

In [ ]:
c[:] = 200
c

array([[200, 200, 200, 200],
       [200, 200, 200, 200]])

In [ ]:
b

array([[ 10, 200, 200, 200, 200],
       [ 90, 200, 200, 200, 200],
       [ 33,  66,  99,  22,  55],
       [ 23,  56,  98,  45,  65]])

### Copy

In [ ]:
b = np.array([[10,32,6,7,8], [90, 45, 32 , 89, 50],
              [33, 66, 99, 22, 55], [23, 56, 98, 45, 65]])
b

array([[10, 32,  6,  7,  8],
       [90, 45, 32, 89, 50],
       [33, 66, 99, 22, 55],
       [23, 56, 98, 45, 65]])

In [ ]:
d = b[:2,1:].copy()
d

array([[32,  6,  7,  8],
       [45, 32, 89, 50]])

In [ ]:
d[:] = 500
d

array([[500, 500, 500, 500],
       [500, 500, 500, 500]])

In [ ]:
b

array([[10, 32,  6,  7,  8],
       [90, 45, 32, 89, 50],
       [33, 66, 99, 22, 55],
       [23, 56, 98, 45, 65]])

### Selection

In [ ]:
a = np.arange(30, 45)
a

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44])

In [ ]:
b = a < 40
b

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False, False, False, False, False])

In [ ]:
a[b]

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [ ]:
c = a[a < 35]
c

array([30, 31, 32, 33, 34])

## <font color='orange'>5. NumPy Operations</font>

### Arithmatic operations

In [ ]:
a = np.arange(10, 25)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
a + a

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48])

In [ ]:
a - a

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
a * a

In [ ]:
a / a

In [ ]:
a ** 2

array([100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400, 441, 484,
       529, 576])

In [ ]:
100/ a

array([10.        ,  9.09090909,  8.33333333,  7.69230769,  7.14285714,
        6.66666667,  6.25      ,  5.88235294,  5.55555556,  5.26315789,
        5.        ,  4.76190476,  4.54545455,  4.34782609,  4.16666667])

### Universal operations

In [ ]:
a = np.arange(10, 30, 3)
a

array([10, 13, 16, 19, 22, 25, 28])

In [ ]:
np.sqrt(a)  #Square root of each element

array([3.16227766, 3.60555128, 4.        , 4.35889894, 4.69041576,
       5.        , 5.29150262])

In [ ]:
np.exp(a)  #Exponent of each element

array([2.20264658e+04, 4.42413392e+05, 8.88611052e+06, 1.78482301e+08,
       3.58491285e+09, 7.20048993e+10, 1.44625706e+12])

In [ ]:
np.square(a) #Square of each element

array([100, 169, 256, 361, 484, 625, 784])

In [ ]:
np.sin(a)  #Trignometric sine

array([-0.54402111,  0.42016704, -0.28790332,  0.14987721, -0.00885131,
       -0.13235175,  0.27090579])

In [ ]:
np.log(a)  #log

array([2.30258509, 2.56494936, 2.77258872, 2.94443898, 3.09104245,
       3.21887582, 3.33220451])

### Universal operations. . .

In [ ]:
a = np.random.rand(4,5)
a

array([[0.01936696, 0.67883553, 0.21162812, 0.26554666, 0.49157316],
       [0.05336255, 0.57411761, 0.14672857, 0.58930554, 0.69975836],
       [0.10233443, 0.41405599, 0.69440016, 0.41417927, 0.04995346],
       [0.53589641, 0.66379465, 0.51488911, 0.94459476, 0.58655504]])

In [ ]:
np.round(a,2)  #rounding to 2 decimal places

array([[0.02, 0.68, 0.21, 0.27, 0.49],
       [0.05, 0.57, 0.15, 0.59, 0.7 ],
       [0.1 , 0.41, 0.69, 0.41, 0.05],
       [0.54, 0.66, 0.51, 0.94, 0.59]])

In [ ]:
np.round(a)  #rounding to 0 decimal places

array([[0., 1., 0., 0., 0.],
       [0., 1., 0., 1., 1.],
       [0., 0., 1., 0., 0.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.std(a)  #Calculate standard variance

0.25831736843541603

In [ ]:
np.var(a) #Calculate variance

0.06672786283539846

In [ ]:
np.mean(a) #Mean / average

0.43254381552182375

### Unique operation

In [ ]:
a = np.array(['Orange', 'Mango', 'Apple', 'Apple', 'Banana', 'Mango', 'banana'])
a

array(['Orange', 'Mango', 'Apple', 'Apple', 'Banana', 'Mango', 'banana'],
      dtype='<U6')

In [ ]:
np.unique(a)

array(['Apple', 'Banana', 'Mango', 'Orange', 'banana'], dtype='<U6')

## <font color='brown'>6. Storing and reading NumPy</font>

### Saving and Restoring

In [ ]:
array_1 = np.arange(10, 20)
array_2 = np.arange(30,50, 3)

In [ ]:
np.save('ar1file',  #File name , will be saved with .npy extension
        array_1 ) #Array to be saved

In [ ]:
!ls -l

total 8
-rw-r--r-- 1 root root  208 Jan 20 11:34 ar1file.npy
drwxr-xr-x 1 root root 4096 Jan 18 14:55 sample_data


In [ ]:
np.load('ar1file.npy')

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

### Saving two arrays into single file

In [ ]:
np.savez('ar_multi',  #file name, extension will be .npz
         a=array_1,
         b=array_2)

In [ ]:
!ls -l

total 12
-rw-r--r-- 1 root root  208 Jan 20 11:34 ar1file.npy
-rw-r--r-- 1 root root  626 Jan 20 11:35 ar_multi.npz
drwxr-xr-x 1 root root 4096 Jan 18 14:55 sample_data


In [ ]:
saved_array = np.load('ar_multi.npz')

In [ ]:
saved_array['a']

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

### Saving as txt file

In [ ]:
np.savetxt('ar_1.txt', array_1, delimiter=',')

In [ ]:
np.loadtxt('ar_1.txt', delimiter=',')